weather_ranges = Condition.create([maxtemp: 100 , mintemp: 80 , precipitation: , humidity: ],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],)
