weather_ranges = Condition.create([maxtemp: 100 , mintemp: 80 , precipitation: , humidity: ],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],
                                  [maxtemp: , mintemp:  , precipitation: , humidity:],)

clothing_pieces = Garment.create([name: 'shirt'],
                                [name: 'pants'],
                                [name: 'dress', is_female: true],
                                [name: 'sweater'],
                                [name: 'scarf'],
                                [name: 'socks'],
                                [name: 'skirt'],
                                [name: ],
                                [name: ],
                                [name: ],
                                [name: ],
                                [name: ],
                                [name: ],
                                [name: ],
                                )
